public static class GentUpgradesConstants
{
	public const string UI_GENT_UPGRADES_GENT_DOOR = "UI_GENT_UPGRADES_GENT_DOOR";

	public const string UI_GENT_UPGRADES_GENT_DOOR_MESSAGE = "UI_GENT_UPGRADES_GENT_DOOR_MESSAGE";

	public const string UI_GENT_UPGRADES_GENT_IMPACT = "UI_GENT_UPGRADES_GENT_IMPACT";

	public const string UI_GENT_UPGRADES_GENT_IMPACT_MESSAGE = "UI_GENT_UPGRADES_GENT_IMPACT_MESSAGE";

	public const string UI_GENT_UPGRADES_GENT_STUN = "UI_GENT_UPGRADES_GENT_STUN";

	public const string UI_GENT_UPGRADES_GENT_STUN_MESSAGE = "UI_GENT_UPGRADES_GENT_STUN_MESSAGE";

	public const string UI_GENT_UPGRADES_TITLE = "UI_GENT_UPGRADES_TITLE";

	public const string UI_GENT_UPGRADES_DESCRIPTION = "UI_GENT_UPGRADES_DESCRIPTION";

	public const string UI_GENT_UPGRADES_REQUIRED = "UI_GENT_UPGRADES_REQUIRED";
}
