public static class InfoPopupConstants
{
	public const string UI_INFO_POPUP_FOOD = "UI_INFO_POPUP_FOOD";

	public const string UI_INFO_POPUP_FOOD_HEADER = "UI_INFO_POPUP_FOOD_HEADER";

	public const string UI_INFO_POPUP_FOOD_MESSAGE = "UI_INFO_POPUP_FOOD_MESSAGE";

	public const string UI_INFO_POPUP_STEALTH = "UI_INFO_POPUP_STEALTH";

	public const string UI_INFO_POPUP_STEALTH_HEADER = "UI_INFO_POPUP_STEALTH_HEADER";

	public const string UI_INFO_POPUP_STEALTH_MESSAGE = "UI_INFO_POPUP_STEALTH_MESSAGE";

	public const string UI_INFO_POPUP_GENT_PIPE = "UI_INFO_POPUP_GENT_PIPE";

	public const string UI_INFO_POPUP_GENT_PIPE_HEADER = "UI_INFO_POPUP_GENT_PIPE_HEADER";

	public const string UI_INFO_POPUP_GENT_PIPE_MESSAGE = "UI_INFO_POPUP_GENT_PIPE_MESSAGE";

	public const string UI_INFO_POPUP_BANISH = "UI_INFO_POPUP_BANISH";

	public const string UI_INFO_POPUP_BANISH_HEADER = "UI_INFO_POPUP_BANISH_HEADER";

	public const string UI_INFO_POPUP_BANISH_MESSAGE = "UI_INFO_POPUP_BANISH_MESSAGE";

	public const string UI_INFO_POPUP_INK_DEMON = "UI_INFO_POPUP_INK_DEMON";

	public const string UI_INFO_POPUP_INK_DEMON_HEADER = "UI_INFO_POPUP_INK_DEMON_HEADER";

	public const string UI_INFO_POPUP_INK_DEMON_MESSAGE = "UI_INFO_POPUP_INK_DEMON_MESSAGE";

	public const string UI_INFO_POPUP_FLOW = "UI_INFO_POPUP_FLOW";

	public const string UI_INFO_POPUP_FLOW_HEADER = "UI_INFO_POPUP_FLOW_HEADER";

	public const string UI_INFO_POPUP_FLOW_MESSAGE = "UI_INFO_POPUP_FLOW_MESSAGE";

	public const string UI_INFO_POPUP_GENT_LOCK = "UI_INFO_POPUP_GENT_LOCK";

	public const string UI_INFO_POPUP_GENT_LOCK_HEADER = "UI_INFO_POPUP_GENT_LOCK_HEADER";

	public const string UI_INFO_POPUP_GENT_LOCK_MESSAGE = "UI_INFO_POPUP_GENT_LOCK_MESSAGE";

	public const string UI_INFO_POPUP_FAST_TRAVEL = "UI_INFO_POPUP_FAST_TRAVEL";

	public const string UI_INFO_POPUP_FAST_TRAVEL_HEADER = "UI_INFO_POPUP_FAST_TRAVEL_HEADER";

	public const string UI_INFO_POPUP_FAST_TRAVEL_MESSAGE = "UI_INFO_POPUP_FAST_TRAVEL_MESSAGE";

	public const string UI_INFO_POPUP_SUBWAY = "UI_INFO_POPUP_SUBWAY";

	public const string UI_INFO_POPUP_SUBWAY_HEADER = "UI_INFO_POPUP_SUBWAY_HEADER";

	public const string UI_INFO_POPUP_SUBWAY_MESSAGE = "UI_INFO_POPUP_SUBWAY_MESSAGE";

	public const string UI_INFO_POPUP_SHOCK_PIPE = "UI_INFO_POPUP_SHOCK_PIPE";

	public const string UI_INFO_POPUP_SHOCK_PIPE_HEADER = "UI_INFO_POPUP_SHOCK_PIPE_HEADER";

	public const string UI_INFO_POPUP_SHOCK_PIPE_MESSAGE = "UI_INFO_POPUP_SHOCK_PIPE_MESSAGE";

	public const string UI_INFO_POPUP_STUN_PIPE = "UI_INFO_POPUP_STUN_PIPE";

	public const string UI_INFO_POPUP_STUN_PIPE_HEADER = "UI_INFO_POPUP_STUN_PIPE_HEADER";

	public const string UI_INFO_POPUP_STUN_PIPE_MESSAGE = "UI_INFO_POPUP_STUN_PIPE_MESSAGE";

	public const string UI_INFO_POPUP_DISMISS = "UI_INFO_POPUP_DISMISS";

	public const string UI_INFO_POPUP_DISMISS_PRESS = "UI_INFO_POPUP_DISMISS_PRESS";
}
