public static class MenuConstants
{
	public const string MENU_PHOTOSENSITIVE_WARNING_HEADER = "MENU_PHOTOSENSITIVE_WARNING_HEADER";

	public const string MENU_PHOTOSENSITIVE_WARNING_BODY = "MENU_PHOTOSENSITIVE_WARNING_BODY";

	public const string MENU_YES = "MENU_YES";

	public const string MENU_NO = "MENU_NO";

	public const string MENU_SELECT = "MENU_SELECT";

	public const string MENU_BACK = "MENU_BACK";

	public const string MENU_START_GAME = "MENU_START_GAME";

	public const string MENU_CONTINUE = "MENU_CONTINUE";

	public const string MENU_NEW_GAME = "MENU_NEW_GAME";

	public const string MENU_NEW_GAME_DIFFICULTY_HEADER = "MENU_NEW_GAME_DIFFICULTY_HEADER";

	public const string MENU_NEW_GAME_DIFFICULTY_DESCRIPTION = "MENU_NEW_GAME_DIFFICULTY_DESCRIPTION";

	public const string MENU_NEW_GAME_DIFFICULTY_EASY = "MENU_NEW_GAME_DIFFICULTY_EASY";

	public const string MENU_NEW_GAME_DIFFICULTY_EASY_DESCRIPTION = "MENU_NEW_GAME_DIFFICULTY_EASY_DESCRIPTION";

	public const string MENU_NEW_GAME_DIFFICULTY_NORMAL = "MENU_NEW_GAME_DIFFICULTY_NORMAL";

	public const string MENU_NEW_GAME_DIFFICULTY_NORMAL_DESCRIPTION = "MENU_NEW_GAME_DIFFICULTY_NORMAL_DESCRIPTION";

	public const string MENU_NEW_GAME_DIFFICULTY_HARD = "MENU_NEW_GAME_DIFFICULTY_HARD";

	public const string MENU_NEW_GAME_DIFFICULTY_HARD_DESCRIPTION = "MENU_NEW_GAME_DIFFICULTY_HARD_DESCRIPTION";

	public const string MENU_NEW_GAME_START_HEADER = "MENU_NEW_GAME_START_HEADER";

	public const string MENU_NEW_GAME_START_SUB_HEADER = "MENU_NEW_GAME_START_SUB_HEADER";

	public const string MENU_LOAD_AUTOSAVE = "MENU_LOAD_AUTOSAVE";

	public const string MENU_LOAD_GAME = "MENU_LOAD_GAME";

	public const string MENU_OPTIONS = "MENU_OPTIONS";

	public const string MENU_OPTIONS_AUDIO = "MENU_OPTIONS_AUDIO";

	public const string MENU_OPTIONS_AUDIO_VOLUME_MASTER = "MENU_OPTIONS_AUDIO_VOLUME_MASTER";

	public const string MENU_OPTIONS_AUDIO_VOLUME_EFFECTS = "MENU_OPTIONS_AUDIO_VOLUME_EFFECTS";

	public const string MENU_OPTIONS_AUDIO_VOLUME_MUSIC = "MENU_OPTIONS_AUDIO_VOLUME_MUSIC";

	public const string MENU_OPTIONS_AUDIO_VOLUME_DIALOGUE = "MENU_OPTIONS_AUDIO_VOLUME_DIALOGUE";

	public const string MENU_OPTIONS_AUDIO_SUBTITLES = "MENU_OPTIONS_AUDIO_SUBTITLES";

	public const string MENU_OPTIONS_AUDIO_LANGUAGE = "MENU_OPTIONS_AUDIO_LANGUAGE";

	public const string MENU_OPTIONS_AUDIO_LANGUAGE_ENGLISH = "MENU_OPTIONS_AUDIO_LANGUAGE_ENGLISH";

	public const string MENU_OPTIONS_AUDIO_LANGUAGE_FRENCH = "MENU_OPTIONS_AUDIO_LANGUAGE_FRENCH";

	public const string MENU_OPTIONS_AUDIO_LANGUAGE_ITALIAN = "MENU_OPTIONS_AUDIO_LANGUAGE_ITALIAN";

	public const string MENU_OPTIONS_AUDIO_LANGUAGE_GERMAN = "MENU_OPTIONS_AUDIO_LANGUAGE_GERMAN";

	public const string MENU_OPTIONS_AUDIO_LANGUAGE_SPANISH = "MENU_OPTIONS_AUDIO_LANGUAGE_SPANISH";

	public const string MENU_OPTIONS_AUDIO_LANGUAGE_JAPANESE = "MENU_OPTIONS_AUDIO_LANGUAGE_JAPANESE";

	public const string MENU_OPTIONS_AUDIO_LANGUAGE_RUSSIAN = "MENU_OPTIONS_AUDIO_LANGUAGE_RUSSIAN";

	public const string MENU_OPTIONS_AUDIO_LANGUAGE_UKRANIAN = "MENU_OPTIONS_AUDIO_LANGUAGE_UKRANIAN";

	public const string MENU_OPTIONS_AUDIO_LANGUAGE_BRAZILIAN_PORTUGUESE = "MENU_OPTIONS_AUDIO_LANGUAGE_BRAZILIAN_PORTUGUESE";

	public const string MENU_OPTIONS_AUDIO_LANGUAGE_SIMPLIFIED_CHINESE = "MENU_OPTIONS_AUDIO_LANGUAGE_SIMPLIFIED_CHINESE";

	public const string MENU_OPTIONS_GRAPHICS = "MENU_OPTIONS_GRAPHICS";

	public const string MENU_OPTIONS_GRAPHICS_QUALITY = "MENU_OPTIONS_GRAPHICS_QUALITY";

	public const string MENU_OPTIONS_GRAPHICS_QUALITY_LOW = "MENU_OPTIONS_GRAPHICS_QUALITY_LOW";

	public const string MENU_OPTIONS_GRAPHICS_QUALITY_MEDIUM = "MENU_OPTIONS_GRAPHICS_QUALITY_MEDIUM";

	public const string MENU_OPTIONS_GRAPHICS_QUALITY_HIGH = "MENU_OPTIONS_GRAPHICS_QUALITY_HIGH";

	public const string MENU_OPTIONS_GRAPHICS_RESOLUTION = "MENU_OPTIONS_GRAPHICS_RESOLUTION";

	public const string MENU_OPTIONS_GRAPHICS_FULLSCREEN = "MENU_OPTIONS_GRAPHICS_FULLSCREEN";

	public const string MENU_OPTIONS_GRAPHICS_BRIGHTNESS = "MENU_OPTIONS_GRAPHICS_BRIGHTNESS";

	public const string MENU_OPTIONS_GRAPHICS_DOF = "MENU_OPTIONS_GRAPHICS_DOF";

	public const string MENU_OPTIONS_GRAPHICS_BLOOM = "MENU_OPTIONS_GRAPHICS_BLOOM";

	public const string MENU_OPTIONS_GRAPHICS_AMBIENT_OCCLUSION = "MENU_OPTIONS_GRAPHICS_AMBIENT_OCCLUSION";

	public const string MENU_OPTIONS_GRAPHICS_MOTION_BLUR = "MENU_OPTIONS_GRAPHICS_MOTION_BLUR";

	public const string MENU_OPTIONS_GRAPHICS_ANTI_ALIASING = "MENU_OPTIONS_GRAPHICS_ANTI_ALIASING";

	public const string MENU_OPTIONS_GRAPHICS_VSYNC = "MENU_OPTIONS_GRAPHICS_VSYNC";

	public const string MENU_OPTIONS_GRAPHICS_VSYNC_OFF = "MENU_OPTIONS_GRAPHICS_VSYNC_OFF";

	public const string MENU_OPTIONS_GRAPHICS_VSYNC_LOW = "MENU_OPTIONS_GRAPHICS_VSYNC_LOW";

	public const string MENU_OPTIONS_GRAPHICS_VSYNC_HIGH = "MENU_OPTIONS_GRAPHICS_VSYNC_HIGH";

	public const string MENU_OPTIONS_CONTROLS = "MENU_OPTIONS_CONTROLS";

	public const string MENU_OPTIONS_CONTROLS_SENSITIVITY = "MENU_OPTIONS_CONTROLS_SENSITIVITY";

	public const string MENU_OPTIONS_CONTROLS_INVERTED = "MENU_OPTIONS_CONTROLS_INVERTED";

	public const string MENU_OPTIONS_CONTROLS_CROSSHAIR = "MENU_OPTIONS_CONTROLS_CROSSHAIR";

	public const string MENU_OPTIONS_CONTROLS_VIEW_SWAYING = "MENU_OPTIONS_CONTROLS_VIEW_SWAYING";

	public const string MENU_OPTIONS_CONTROLS_SMOOTH_CAMERA = "MENU_OPTIONS_CONTROLS_SMOOTH_CAMERA";

	public const string MENU_OPTIONS_CONTROLS_RUMBLE = "MENU_OPTIONS_CONTROLS_RUMBLE";

	public const string MENU_SETTINGS_SAVE_GAME = "MENU_SETTINGS_SAVE_GAME";

	public const string MENU_SETTINGS_CANNOT_SAVE = "MENU_SETTINGS_CANNOT_SAVE";

	public const string MENU_SETTINGS_SAVE_GAME_SAVE_SLOT = "MENU_SETTINGS_SAVE_GAME_SAVE_SLOT";

	public const string MENU_SETTINGS_SAVE_GAME_NEW = "MENU_SETTINGS_SAVE_GAME_NEW";

	public const string MENU_SETTINGS_SAVE_GAME_HEADER = "MENU_SETTINGS_SAVE_GAME_HEADER";

	public const string MENU_SETTINGS_SAVE_GAME_SUB_HEADER = "MENU_SETTINGS_SAVE_GAME_SUB_HEADER";

	public const string MENU_SETTINGS_LOAD_GAME = "MENU_SETTINGS_LOAD_GAME";

	public const string MENU_SETTINGS_LOAD_GAME_AUTOSAVE = "MENU_SETTINGS_LOAD_GAME_AUTOSAVE";

	public const string MENU_SETTINGS_LOAD_GAME_DIFFICULTY = "MENU_SETTINGS_LOAD_GAME_DIFFICULTY";

	public const string MENU_SETTINGS_LOAD_GAME_HEADER = "MENU_SETTINGS_LOAD_GAME_HEADER";

	public const string MENU_SETTINGS_LOAD_GAME_SUB_HEADER = "MENU_SETTINGS_LOAD_GAME_SUB_HEADER";

	public const string MENU_SETTINGS_MAIN_MENU = "MENU_SETTINGS_MAIN_MENU";

	public const string MENU_SETTINGS_MAIN_MENU_HEADDER = "MENU_SETTINGS_MAIN_MENU_HEADDER";

	public const string MENU_CREDITS = "MENU_CREDITS";

	public const string MENU_QUIT = "MENU_QUIT";

	public const string MENU_QUIT_HEADER = "MENU_QUIT_HEADER";

	public const string MENU_QUIT_SUB_HEADER = "MENU_QUIT_SUB_HEADER";

	public const string MENU_GAME_OVER_HEADER = "MENU_GAME_OVER_HEADER";

	public const string MENU_GAME_OVER_SUB_HEADER = "MENU_GAME_OVER_SUB_HEADER";

	public const string MENU_WEAPON_GENT_LOCK_DESCRIPTION = "MENU_WEAPON_GENT_LOCK_DESCRIPTION";

	public const string MENU_WEAPON_SHOCK_PIPE_DESCRIPTION = "MENU_WEAPON_SHOCK_PIPE_DESCRIPTION";

	public const string MENU_WEAPON_STUN_PIPE_DESCRIPTION = "MENU_WEAPON_STUN_PIPE_DESCRIPTION";

	public const string MENU_SEASONAL = "MENU_SEASONAL";

	public const string MENU_ARCHIVES = "MENU_ARCHIVES";

	public const string MENU_SETTINGS_CANNOT_LOAD = "MENU_SETTINGS_CANNOT_LOAD";

	public const string MENU_NAVIGATION = "MENU_NAVIGATION";

	public const string MENU_OPTIONS_CONTROLS_VIBRATION = "MENU_OPTIONS_CONTROLS_VIBRATION";

	public const string MENU_WEAPON_CONTENT_TITLE = "MENU_WEAPON_CONTENT_TITLE";

	public const string MENU_WEAPON_CONTENT_UNLOCK = "MENU_WEAPON_CONTENT_UNLOCK";

	public const string MENU_WEAPON_CONTENT_LOCKED = "MENU_WEAPON_CONTENT_LOCKED";

	public const string MENU_ABILITY_CONTENT_TITLE = "MENU_ABILITY_CONTENT_TITLE";

	public const string MENU_ABILITY_CONTENT_UNLOCK = "MENU_ABILITY_CONTENT_UNLOCK";

	public const string MENU_ABILITY_CONTENT_LOCKED = "MENU_ABILITY_CONTENT_LOCKED";

	public const string MENU_GAME_MENU_OBJECTIVES = "MENU_GAME_MENU_OBJECTIVES";

	public const string MENU_GAME_MENU_LOCATION = "MENU_GAME_MENU_LOCATION";
}
