public static class NotificationConstants
{
	public const string NOTIFICATION_UPGRADE = "NOTIFICATION_UPGRADE";

	public const string NOTIFICATION_COLLECTED = "NOTIFICATION_COLLECTED";

	public const string NOTIFICATION_AUDIO_LOG = "NOTIFICATION_AUDIO_LOG";

	public const string NOTIFICATION_AUDIO_LOG_MENU = "NOTIFICATION_AUDIO_LOG_MENU";

	public const string NOTIFICATION_MEMO = "NOTIFICATION_MEMO";

	public const string NOTIFICATION_MEMO_MENU = "NOTIFICATION_MEMO_MENU";

	public const string NOTIFICATION_MEMORY = "NOTIFICATION_MEMORY";

	public const string NOTIFICATION_MEMORY_MENU = "NOTIFICATION_MEMORY_MENU";

	public const string NOTIFICATION_MENU_01 = "NOTIFICATION_MENU_01";

	public const string NOTIFICATION_MENU_02 = "NOTIFICATION_MENU_02";

	public const string NOTIFICATION_MENU_03 = "NOTIFICATION_MENU_03";

	public const string NOTIFICATION_MENU_04 = "NOTIFICATION_MENU_04";

	public const string NOTIFICATION_GAME_SAVED = "NOTIFICATION_GAME_SAVED";

	public const string NOTIFICATION_GAME_LOADED = "NOTIFICATION_GAME_LOADED";

	public const string NOTIFICATION_LOOT = "NOTIFICATION_LOOT";

	public const string NOTIFICATION_LOOT_SLUG = "NOTIFICATION_LOOT_SLUG";

	public const string NOTIFICATION_LOOT_SLUGS = "NOTIFICATION_LOOT_SLUGS";

	public const string NOTIFICATION_LOOT_EAT = "NOTIFICATION_LOOT_EAT";

	public const string NOTIFICATION_LOOT_BACON_SOUP = "NOTIFICATION_LOOT_BACON_SOUP";

	public const string NOTIFICATION_LOOT_BENDY_BAR = "NOTIFICATION_LOOT_BENDY_BAR";

	public const string NOTIFICATION_LOOT_SANDWHICH = "NOTIFICATION_LOOT_SANDWHICH";

	public const string NOTIFICATION_LOOT_DONUT = "NOTIFICATION_LOOT_DONUT";

	public const string NOTIFICATION_LOOT_CHIPS = "NOTIFICATION_LOOT_CHIPS";

	public const string NOTIFICATION_LOOT_CRACKERS = "NOTIFICATION_LOOT_CRACKERS";

	public const string NOTIFICATION_LOOT_MEAT = "NOTIFICATION_LOOT_MEAT";

	public const string NOTIFICATION_LOOT_NUTS = "NOTIFICATION_LOOT_NUTS";

	public const string NOTIFICATION_LOOT_GENT_TOOLKIT = "NOTIFICATION_LOOT_GENT_TOOLKIT";

	public const string NOTIFICATION_LOOT_GENT_PARTS = "NOTIFICATION_LOOT_GENT_PARTS";

	public const string NOTIFICATION_LOOT_GENT_BATTERY = "NOTIFICATION_LOOT_GENT_BATTERY";

	public const string NOTIFICATION_LOOT_GENT_BATTERIES = "NOTIFICATION_LOOT_GENT_BATTERIES";

	public const string NOTIFICATION_LOOT_GENT_CARD = "NOTIFICATION_LOOT_GENT_CARD";

	public const string NOTIFICATION_LOOT_SPENT = "NOTIFICATION_LOOT_SPENT";

	public const string NOTIFICATION_SCHEMATIC = "NOTIFICATION_SCHEMATIC";

	public const string NOTIFICATION_GENT_PIPE = "NOTIFICATION_GENT_PIPE";

	public const string NOTIFICATION_GENT_PIPE_UPGRADED = "NOTIFICATION_GENT_PIPE_UPGRADED";

	public const string NOTIFICATION_GENT_PIPE_GENT_LOCK = "NOTIFICATION_GENT_PIPE_GENT_LOCK";

	public const string NOTIFICATION_GENT_PIPE_SHOCK_PIPE = "NOTIFICATION_GENT_PIPE_SHOCK_PIPE";

	public const string NOTIFICATION_GENT_PIPE_STUN_PIPE = "NOTIFICATION_GENT_PIPE_STUN_PIPE";

	public const string NOTIFICATION_LOOT_GENT_BATTERY_CASING = "NOTIFICATION_LOOT_GENT_BATTERY_CASING";

	public const string NOTIFICATION_AUTOSAVE = "NOTIFICATION_AUTOSAVE";

	public const string NOTIFICATION_PICTURE = "NOTIFICATION_PICTURE";

	public const string NOTIFICATION_INK_DEMON = "NOTIFICATION_INK_DEMON";

	public const string NOTIFICATION_OBJECTIVE_INK_HEART = "NOTIFICATION_OBJECTIVE_INK_HEART";

	public const string NOTIFICATION_OBJECTIVE_KEY = "NOTIFICATION_OBJECTIVE_KEY";

	public const string NOTIFICATION_EQUIP_GENT_PIPE = "NOTIFICATION_EQUIP_GENT_PIPE";

	public const string NOTIFICATION_BANISH_ACQUIRED = "NOTIFICATION_BANISH_ACQUIRED";

	public const string NOTIFICATION_SEASONAL_PRESENT = "NOTIFICATION_SEASONAL_PRESENT";

	public const string NOTIFICATION_SEASONAL_WINTER_HAT = "NOTIFICATION_SEASONAL_WINTER_HAT";

	public const string NOTIFICATION_SEASONAL_HALLOWEEN_HAT = "NOTIFICATION_SEASONAL_HALLOWEEN_HAT";

	public const string NOTIFICATION_TEXT_PRESS = "NOTIFICATION_TEXT_PRESS";

	public const string NOTIFICATION_TEXT_CROUCH = "NOTIFICATION_TEXT_CROUCH";

	public const string NOTIFICATION_TEXT_RUN = "NOTIFICATION_TEXT_RUN";

	public const string NOTIFICATION_TEXT_HOLD = "NOTIFICATION_TEXT_HOLD";

	public const string NOTIFICATION_TEXT_FLOW = "NOTIFICATION_TEXT_FLOW";

	public const string NOTIFICATION_TEXT_SMASH = "NOTIFICATION_TEXT_SMASH";
}
